# Base image
FROM python:3.10-alpine

# Set the working directory
WORKDIR /app

# Install system dependencies
RUN apk update && \
    apk add --no-cache gcc musl-dev libffi-dev openssl-dev g++ make

# Install PyTorch
RUN apk add --no-cache libstdc++ libgcc
RUN pip install torch==2.0.0 torchvision

# Copy the requirements.txt file to the working directory
COPY requirements.txt .

# Install project dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code to the working directory
COPY . /app

ENV FLASK_APP=app.py
# 1: dev 환경
ENV FLASK_DEBUG=1

# Expose the port that Flask app will be served on
EXPOSE 5000

# Start the Flask app
CMD ["python", "app.py"]