# Base image
FROM python:3.10-slim-buster

# Set working directory
WORKDIR /app

# Copy requirements file
COPY requirements-linux.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements-linux.txt

# Copy application code
COPY . /app

ENV FLASK_APP=app.py
# 0: prod 환경
ENV FLASK_DEBUG=0

# Expose the port that Flask app will be served on
EXPOSE 5000

# Start the Flask app
CMD ["python", "app.py"]