# Base image
FROM python:3.10-alpine

# Install system dependencies
RUN apk add --no-cache \
    libstdc++

# Install PyTorch dependencies
RUN apk add --no-cache \
    build-base \
    g++ \
    git \
    libjpeg \
    libjpeg-turbo-dev \
    libpng \
    libpng-dev \
    openblas-dev

# Set the working directory
WORKDIR /app

# Copy the requirements.txt file to the working directory
COPY requirements.txt .

# Install project dependencies
RUN pip install --no-cache-dir --upgrade pip setuptools
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code to the working directory
COPY . /app

ENV FLASK_APP=app.py
# 1: dev 환경
ENV FLASK_DEBUG=1

# Expose the port that Flask app will be served on
EXPOSE 5000

# Start the Flask app
CMD ["python", "app.py"]